-- 코드를 입력하세요
SELECT CAR_ID
     , DECODE(AVAILABILITY_CNT, 0, '대여 가능', '대여중') AS AVAILABILITY
  FROM(
SELECT A.CAR_ID
     , SUM(CASE WHEN TO_DATE('20221016', 'YYYYMMDD') BETWEEN A.START_DATE AND A.END_DATE THEN 1 ELSE 0 END) AS AVAILABILITY_CNT
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 GROUP BY A.CAR_ID)
 ORDER BY CAR_ID DESC;